In [3]:
import numpy as  np
import pandas as pd

In [9]:
#1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. (Score:1) 

a = np.arange(1,11)
mat = a.reshape(2, 5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
#2. Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. (Score:1) 

b = np.arange(1, 21)
b1 = b[5:16]
print(b1)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [16]:
#3. How to compute the mean, median, and standard deviation of a numpy array?Use the array you created above (Score 1)

mean = np.mean(b)
median = np.median(b)
sd = np.std(b)
print(mean)
print(median)
print(sd)

10.5
10.5
5.766281297335398


In [20]:
#4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)  

x = np.arange(12).reshape(3, 4)
print(x)   

y = np.array([1, 2, 3, 4])   
print(y)

z = x - y
print(z)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3 4]
[[-1 -1 -1 -1]
 [ 3  3  3  3]
 [ 7  7  7  7]]


In [21]:
"""5. Create a dataframe with the following columns: name, age, and gender. The dataframe 
should have 10 rows of data. (Score: 2) 
 
"""


employe = {
    "name": ["Amal", "Jacob", "Sam", "Tony", "Vinu", "Maria", "John", "Hari", "Sunil", "Jishnu"],
    "age": [25, 32, 28, 40, 35, 22, 30, 27, 45, 29],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"]
}

df = pd.DataFrame(employe)
print(df)


     name  age gender
0    Amal   25      M
1   Jacob   32      F
2     Sam   28      M
3    Tony   40      F
4    Vinu   35      M
5   Maria   22      F
6    John   30      M
7    Hari   27      F
8   Sunil   45      M
9  Jishnu   29      F


In [29]:
#1) Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe. (Score: 1) 

df["occupation"] = ["Programmer", "Manager", "Analyst", "Programmer", 
                    "Manager", "Analyst", "Programmer", "Manager", 
                    "Analyst", "Programmer"]
print(df)


     name  age gender  occupation
0    Amal   25      M  Programmer
1   Jacob   32      F     Manager
2     Sam   28      M     Analyst
3    Tony   40      F  Programmer
4    Vinu   35      M     Manager
5   Maria   22      F     Analyst
6    John   30      M  Programmer
7    Hari   27      F     Manager
8   Sunil   45      M     Analyst
9  Jishnu   29      F  Programmer


In [27]:
#2) Select the rows of the dataframe where the age is greater than or equal to 30. (Score: 1)

age_filter = df[df["age"] >= 30]
print(age_filter)


    name  age gender  occupation
1  Jacob   32      F     Manager
3   Tony   40      F  Programmer
4   Vinu   35      M     Manager
6   John   30      M  Programmer
8  Sunil   45      M     Analyst


In [28]:
#3) Convert this dataframe to a CSV file and read that CSV file, and finally display the contents. (Score: 1)

df.to_csv("company.csv", index=False)   
new_df = pd.read_csv("company.csv")     
print(new_df)


     name  age gender  occupation
0    Amal   25      M  Programmer
1   Jacob   32      F     Manager
2     Sam   28      M     Analyst
3    Tony   40      F  Programmer
4    Vinu   35      M     Manager
5   Maria   22      F     Analyst
6    John   30      M  Programmer
7    Hari   27      F     Manager
8   Sunil   45      M     Analyst
9  Jishnu   29      F  Programmer
